package xyz.itihub.distributedtransaction.xa.dao203.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xyz.itihub.distributedtransaction.xa.dao203.model.XA203;
import xyz.itihub.distributedtransaction.xa.dao203.model.XA203Example;

public interface XA203Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_203
     *
     * @mbg.generated Sun Jul 26 13:10:53 CST 2020
     */
    long countByExample(XA203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_203
     *
     * @mbg.generated Sun Jul 26 13:10:53 CST 2020
     */
    int deleteByExample(XA203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_203
     *
     * @mbg.generated Sun Jul 26 13:10:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_203
     *
     * @mbg.generated Sun Jul 26 13:10:53 CST 2020
     */
    int insert(XA203 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_203
     *
     * @mbg.generated Sun Jul 26 13:10:53 CST 2020
     */
    int insertSelective(XA203 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_203
     *
     * @mbg.generated Sun Jul 26 13:10:53 CST 2020
     */
    List<XA203> selectByExample(XA203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_203
     *
     * @mbg.generated Sun Jul 26 13:10:53 CST 2020
     */
    XA203 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_203
     *
     * @mbg.generated Sun Jul 26 13:10:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") XA203 record, @Param("example") XA203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_203
     *
     * @mbg.generated Sun Jul 26 13:10:53 CST 2020
     */
    int updateByExample(@Param("record") XA203 record, @Param("example") XA203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_203
     *
     * @mbg.generated Sun Jul 26 13:10:53 CST 2020
     */
    int updateByPrimaryKeySelective(XA203 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_203
     *
     * @mbg.generated Sun Jul 26 13:10:53 CST 2020
     */
    int updateByPrimaryKey(XA203 record);
}