package xyz.itihub.distributedtransaction.xa.dao202.model;

public class XA202 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_202.id
     *
     * @mbg.generated Sun Jul 26 13:10:05 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_202.name
     *
     * @mbg.generated Sun Jul 26 13:10:05 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_202.id
     *
     * @return the value of xa_202.id
     *
     * @mbg.generated Sun Jul 26 13:10:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_202.id
     *
     * @param id the value for xa_202.id
     *
     * @mbg.generated Sun Jul 26 13:10:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_202.name
     *
     * @return the value of xa_202.name
     *
     * @mbg.generated Sun Jul 26 13:10:05 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_202.name
     *
     * @param name the value for xa_202.name
     *
     * @mbg.generated Sun Jul 26 13:10:05 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}